from __future__ import annotations
from datetime import datetime
from enum import Enum
from typing import List, Optional, Union
from pydantic import BaseModel, Field


# ======================================================
# Core / Shared Schemas
# ======================================================

class PatientOut(BaseModel):
    """
    Patient data exposed to the UI.
    This schema is UI-oriented and may include enriched fields
    (e.g., active device_id), even if they are not directly stored
    in the patient table.

    داده‌های بیمار برای UI.
    این اسکیما لزوماً معادل جدول دیتابیس نیست و می‌تواند
    اطلاعات enrich شده (مثل device_id) داشته باشد.
    """
    patient_id: int
    patient_name: str
    device_id: Optional[str] = None


class VitalOut(BaseModel):
    """
    Enriched vital measurement returned to the UI.

    - device_id is derived from wristband_id
    - patient_name is resolved via assignment -> patient join

    وایتال‌های enrich شده برای UI.
    joinها و mappingها در backend انجام می‌شوند،
    نه در UI.
    """
    device_id: str
    patient_name: str
    heart_rate: int = Field(..., ge=0)
    spo2: int = Field(..., ge=0, le=100)
    temperature: float
    measured_at: datetime


# ======================================================
# Alerts (Domain Contract)
# ======================================================

class AlertSeverity(str, Enum):
    """
    Severity expresses how critical an alert is.

    شدت هشدار (میزان بحرانی بودن)
    """
    WARNING = "WARNING"
    CRITICAL = "CRITICAL"


class AlertStatus(str, Enum):
    """
    Lifecycle status of an alert in the system.

    وضعیت چرخه عمر هشدار در سیستم
    """
    JUST_GENERATED = "JUST_GENERATED"
    ACKNOWLEDGED = "ACKNOWLEDGED"
    # RESOLVED = "RESOLVED"  # future extension


class AlertAckRequest(BaseModel):
    """
    Payload used when acknowledging an alert.

    اطلاعاتی که هنگام acknowledge کردن هشدار ارسال می‌شود.
    """
    reviewed_by: Optional[str] = None
    clinical_note: Optional[str] = None


class AlertListItem(BaseModel):
    """
    UI-ready alert representation.

    This object is fully enriched and ready for display:
    - patient_name and device_id are resolved in backend
    - description comes from DB (message)
    - full_description is generated by backend logic

    نمایش نهایی هشدار برای UI
    """
    alert_id: int
    severity: AlertSeverity
    status: AlertStatus
    alert_type: str
    description: str
    full_description: str
    patient_name: str
    device_id: str
    generated_at: datetime
    metric: str
    value: Optional[Union[int, float, str]] = None


# ======================================================
# Dashboard Overview (Final Contract)
# ======================================================

class SystemOverviewSchema(BaseModel):
    """
    High-level system status indicators.

    شاخص‌های کلی وضعیت سیستم
    """
    active_devices: int = Field(..., ge=0)
    patients_monitored: int = Field(..., ge=0)
    active_alerts: int = Field(..., ge=0)
    last_update: datetime


class DashboardStatsSchema(BaseModel):
    """
    Additional dashboard statistics.

    آمارهای تکمیلی داشبورد
    (در حال حاضر ممکن است برخی مقادیر موقتاً 0 باشند)
    """
    patients_in_risk: int = Field(..., ge=0)
    low_battery_devices: int = Field(..., ge=0)


class RecentAlertSchema(BaseModel):
    """
    Compact alert representation for dashboard widgets.

    نسخه خلاصه هشدار برای ویجت‌های داشبورد
    """
    alert_id: int
    severity: AlertSeverity
    alert_type: str
    description: str
    device_id: str
    generated_at: datetime
    acknowledged: bool
    patient_name: Optional[str] = None


class DashboardOverviewResponse(BaseModel):
    """
    Final response schema for /dashboard/overview endpoint.

    خروجی نهایی endpoint داشبورد
    """
    system_overview: SystemOverviewSchema
    stats: DashboardStatsSchema
    recent_alerts: List[RecentAlertSchema]
# ======================================================

class PatientCreateRequest(BaseModel):
    """
    Payload received from UI to create a new patient.
    """
    name: str = Field(..., min_length=1)
    age: Optional[int] = Field(None, ge=0)
    gender: Optional[str] = Field(None)
    phone: Optional[str] = Field(None)
    threshold_profile: str = Field(...)
    wristband_id: int | None = None


class PatientCreateResponse(BaseModel):
    """
    Response returned after creating a patient.
    """
    patient_id: int
    name: str


class WristbandCreateRequest(BaseModel):
    """
    Create wristband payload from UI.
    ورودی ساخت دستبند از سمت UI
    """
    wristband_id: int = Field(..., ge=1)


class WristbandCreateResponse(BaseModel):
    """
    Create wristband response.
    خروجی ساخت دستبند
    """
    wristband_id: int
    created_at: datetime | None = None